on:
  [workflow_dispatch]
  # pull_request:
  #   paths:
  #   - guestbook-go/**
  # push:
  #   paths:
  #   - guestbook-go/**
  #   branches:        
  #   - master         

name: Build and Push to DockerHub

jobs:
  build-and-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.Dockerhub_User }}
          password: ${{ secrets.Dockerhub_Pass }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          context: guestbook-go/
          push: true
          tags: ${{ secrets.Dockerhub_User }}/guestbook:${{ github.sha }}